server:
  rootPath: /api
  applicationConnectors:
  - type: http
    port: 8080
  adminContextPath: /admin
  adminConnectors:
  - type: http
    port: 8881
database:
  driverClass: org.postgresql.Driver
  user: ${DB_USER}
  password: ${DB_USER_PASSWORD}
  url: ${DB_URL}